version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - adriankrupa
  ignore:
  - dependency-name: pip
    versions:
    - "21.0"
    - 21.0.1
    - "21.1"
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
  - dependency-name: prometheus-client
    versions:
    - 0.10.0
    - 0.10.1
    - 0.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: tox
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.4
    - 3.22.0
    - 3.23.0
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
    - "5.5"
  - dependency-name: aiohttp
    versions:
    - 3.7.3
    - 3.7.4
  - dependency-name: uvloop
    versions:
    - 0.15.0
    - 0.15.2
  - dependency-name: pytest-runner
    versions:
    - 5.3.0
